# Generated by Django 4.1.7 on 2023-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_video_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=TZ6fntlw-TY'),
        ),
    ]
