# Generated by Django 4.1.7 on 2023-06-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='search.userprofile'),
        ),
    ]
